version = 5.2.2
archive_dir = /etc/letsencrypt/archive/2jz.space
cert = /etc/letsencrypt/live/2jz.space/cert.pem
privkey = /etc/letsencrypt/live/2jz.space/privkey.pem
chain = /etc/letsencrypt/live/2jz.space/chain.pem
fullchain = /etc/letsencrypt/live/2jz.space/fullchain.pem
[renewalparams]
account = f991583b4bffaab3293cbfbc999bf276
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 30
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
